apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "notification.fullname" . }}
  namespace: {{ .Release.Namespace | quote }} 
  labels:
    {{- include "notification.labels" . | nindent 4 }}
{{- if .Values.labels }}
{{ toYaml .Values.labels | indent 4 }}
{{- end }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      service: {{ template "notification.fullname" . }}
  template:
    metadata:
      labels:
        service: {{ template "notification.fullname" . }}
    spec:
      containers:
        - name: {{ template "notification.fullname" . }}
          image: "{{ .Values.image.repository }}:{{ default .Chart.AppVersion .Values.image.tag }}"
          ports:
            - containerPort: {{ .Values.containerPort }}
          imagePullPolicy: {{ .Values.imagePullPolicy }}
          envFrom:
            - configMapRef:
                name: {{ .Values.configmap }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      imagePullSecrets:
        - name: {{ .Values.imagePullSecrets }}
      restartPolicy: Always


