apiVersion: v1
kind: Endpoints
metadata:
  name: notification-mysql-connection
  namespace: {{ .Release.Namespace | quote }} 
  labels:
    {{- include "notification.labels" . | nindent 4 }}
{{- if .Values.labels }}
{{ toYaml .Values.labels | indent 4 }}
{{- end }}
subsets:
  - addresses:
      - ip: {{ .Values.mysql_ip }}
    ports:
      - name: notification-mysql
        port: {{ .Values.service.mysqlport }}
        protocol: {{ .Values.protocoltype.tcp }}
