apiVersion: v1
kind: Service
metadata:
  name: notification-mysql-connection
  namespace: {{ .Release.Namespace | quote }} 
  labels:
    {{- include "notification.labels" . | nindent 4 }}
{{- if .Values.labels }}
{{ toYaml .Values.labels | indent 4 }}
{{- end }}
spec:
  ports:
    - name: notification-mysql
      port: {{ .Values.service.mysqlport }}
      protocol: {{ .Values.protocoltype.tcp }} 
      targetPort: {{ .Values.service.mysqlport }}  
  sessionAffinity: {{ .Values.session.sessionAffinity}}
  type: {{ .Values.service.type}}

---
apiVersion: v1
kind: Service
metadata:
  name: {{ template "notification.fullname" . }}
  namespace: {{ .Release.Namespace | quote }} 
  labels:
    {{- include "notification.labels" . | nindent 4 }}
{{- if .Values.labels }}
{{ toYaml .Values.labels | indent 4 }}
{{- end }}
spec:
  ports:
    - name: "80"
      port: {{ .Values.service.port }}
      targetPort: 80
  selector:
    service: {{ template "notification.fullname" . }}
  type: {{ .Values.service.type }}